language: go

sudo: false

os:
  - linux
  - osx 

go:
  - 1.5.x
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - master

script: 
 - go vet ./...
 - go generate
 - go test -v .
 - env CGO_ENABLED=0 go test -v .
 - diff <(gofmt -d .) <("")

matrix:
  allow_failures:
    - go: 'master'
  fast_finish: true
